#!/usr/bin/env sh

LOCAL_REPO="born"

echo
echo "Step 0: Create a new repo at https://github.com/new"
echo
echo "Step 1: Pick your preferred git login method"
echo
echo "1) HTTPS (GitHub Access Token)"
echo "2) SSH"
echo
while true; do
    echo "Please enter 1 or 2: "
    read -r choice
    case $choice in
        1)
            echo
            echo "Step 2: Generate a personal access token at https://github.com/settings/tokens/new"
            echo "Copy and paste it below: "
            read -r ACCESS_TOKEN
            [ -z "$ACCESS_TOKEN" ] && exit 1
            echo
            echo "Step 3: Please enter your GitHub username: "
            read -r USERNAME
            [ -z "$USERNAME" ] && exit 1
            echo
            echo "Step 4: Please enter the name of the repo you created in Step 0: "
            read -r REPONAME
            [ -z "$REPONAME" ] && exit 1
            break
            ;;
        2)
            echo
            echo "Step 2: Copy the SSH link to your repo and paste it below"
            read -r REPO_LINK
            [ -z "$REPO_LINK" ] && exit 1
            USERNAME=${REPO_LINK%/*} # remove suffix after "/"
            USERNAME=${USERNAME#*:} # remove prefix before ":"
            break
            ;;
        *) echo "Invalid option, please enter 1 or 2";;
    esac
done

echo
if [ -z "$REPONAME" ]; then
  echo "Step 3: Enter the date for your contribution (YYYY-MM-DD): "
else
  echo "Step 5: Enter the date for your contribution (YYYY-MM-DD): "
fi
read -r CONTRIBUTION_DATE
# Validate date format
if ! date -d "$CONTRIBUTION_DATE" >/dev/null 2>&1; then
  echo "Invalid date format. Please use YYYY-MM-DD"
  exit 1
fi

[ ! -d "$LOCAL_REPO" ] && mkdir "$LOCAL_REPO"

cd "$LOCAL_REPO" || exit
git init
echo
echo "Last Step: Would you like to add a message to your $LOCAL_REPO repo README? (if not, just press Enter)"
read -r README
if [ -z "$README" ]; then
  echo "Generated by https://github.com/ScreamingHawk/born-script" > README.md
else
  echo "$README" > README.md
  echo "Generated by https://github.com/ScreamingHawk/born-script" >> README.md
fi
git add .
GIT_AUTHOR_DATE="${CONTRIBUTION_DATE}T00:00:00" \
  GIT_COMMITTER_DATE="${CONTRIBUTION_DATE}T00:00:00" \
  git commit -m "$LOCAL_REPO"
if [ -z "$REPO_LINK" ]; then
  git remote add origin "https://${ACCESS_TOKEN}@github.com/${USERNAME}/${REPONAME}.git"
else
  git remote add origin "$REPO_LINK"
fi
git branch -M main
git push -u origin main -f
cd ..
rm -rf "$LOCAL_REPO"

echo
echo "Cool, check your profile now: https://github.com/${USERNAME}"
